#!/usr/bin/env node
/**
 * Promtly bridge — the local half of promtly.dev.
 *
 * A browser tab cannot focus another window, press Ctrl+V, or answer a
 * global hotkey. Those are hard sandbox boundaries, not missing
 * permissions. This process does the parts the page is not allowed to,
 * and it is what turns a web page full of buttons into a launcher:
 *
 *   Ctrl+Alt+Space  summon — remember the window you are in, then bring
 *                   the board up over it. Firing a pad pastes back into
 *                   the window you were in when you summoned it.
 *   Ctrl+Alt+C      capture — copy whatever is selected anywhere on the
 *                   machine and turn it into a new pad.
 *
 * It also SERVES the board at http://127.0.0.1:37222, mirrored from
 * promtly.dev. That is not a convenience: a page on https://promtly.dev
 * cannot reliably reach 127.0.0.1 (Chrome gates public-to-loopback, and
 * a gated request hangs silently — measured, curl answered the identical
 * request in 2 ms). Served from here, the page is SAME-ORIGIN with this
 * process and there is nothing to permit.
 *
 * Targeting is verified, never assumed. If the window switch does not
 * take, it refuses to send the keystroke rather than firing a paste into
 * whatever is still in front.
 *
 * No dependencies. No installer.
 *
 *     node promtly-bridge.mjs
 *
 * Windows only for now (it drives user32 through long-lived PowerShell
 * hosts). Elsewhere it starts, mirrors the board, and says so.
 */

import http from "node:http";
import { spawn } from "node:child_process";
import { createHash } from "node:crypto";
import {
  writeFileSync,
  mkdtempSync,
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  statSync,
  rmSync,
} from "node:fs";
import { tmpdir, homedir, EOL } from "node:os";
import { join, dirname, resolve as resolvePath } from "node:path";

const PORT = Number(process.env.PROMTLY_BRIDGE_PORT || 37222);
const VERSION = "0.7.0";

/** Where the board is served from, for the local mirror. */
const UPSTREAM = (process.env.PROMTLY_UPSTREAM || "https://promtly.dev").replace(/\/+$/, "");

/** The app window's page title, used to find it again on the next summon. */
const LAUNCHER_TITLE = "Promtly Launcher";

const ALLOWED_ORIGINS = new Set([
  "https://promtly.dev",
  "https://www.promtly.dev",
  `http://127.0.0.1:${PORT}`,
  `http://localhost:${PORT}`,
  "http://localhost:3350",
  "http://127.0.0.1:3350",
  ...(process.env.PROMTLY_ALLOW_ORIGIN
    ? process.env.PROMTLY_ALLOW_ORIGIN.split(",").map((s) => s.trim()).filter(Boolean)
    : []),
]);

/** Paths this process answers itself; everything else is the mirrored board. */
const API_PATHS = new Set([
  "/health",
  "/paste",
  "/copy",
  "/captures",
  "/captures/clear",
  "/local/theme.css",
  "/local/custom.js",
  "/local/version",
  "/local/theme",
  "/dismiss",
  "/chairs",
  "/chairs/seat",
  "/chairs/unseat",
  "/relay",
  "/window",
  "/startup",
  "/update",
]);

// ---------------------------------------------------------------------------
// The harness layer.
//
// ⭐ This is what makes the client yours rather than mine. The deployed board
// ships the defaults; these files sit on YOUR machine, and the bridge injects
// them into the page it serves. So restyling the launcher, or adding a
// behaviour, is an edit to one small local file — which means you can hand it
// to Claude or ChatGPT ("read PROMTLY-CUSTOMIZE.md and make the launcher look
// like a terminal") instead of forking anything.
//
// The page polls /local/version, so an edit lands in the open window in about
// a second without a reload. That loop is the whole point: an agent changes
// the file, you watch it change.
// ---------------------------------------------------------------------------

// The agent-facing contract. Written next to the bridge on first run so you
// can say "read PROMTLY-CUSTOMIZE.md and restyle this" and have it work the
// first time, rather than the model guessing at class names.
//
// ⚠ No backticks anywhere in this string: it is a template literal, and an
// unescaped backtick ends it and takes the rest of the file with it. Markdown
// code spans here use indented blocks and quotes instead.
const CUSTOMIZE_GUIDE = String.raw`
# Customising your Promtly

Generated by the bridge, and REWRITTEN whenever it changes - the token table
below has to match what the app actually ships or an assistant will style
against numbers that no longer exist. Your edits belong in
promtly-local/theme.css, which the bridge never touches once it exists.

This client is a harness. The board and launcher are served from promtly.dev,
but the LOOK AND BEHAVIOUR are yours - they come from files on this machine
that the bridge injects into the page.

You are meant to change these with an assistant. Hand this file to Claude or
ChatGPT and ask for what you want.

## The files

    promtly-local/theme.css     your styles. Anything here wins.
    promtly-local/custom.js     optional. Loaded only if it exists.

Save either one and the open window picks it up in about a second. No reload,
no rebuild, nothing to restart.

## Tokens

Redefine any of these inside a :root block in theme.css. COLOURS ARE
SPACE-SEPARATED RGB CHANNELS, not hex, so the opacity modifiers keep working.

    --c-bg                  11 15 20        page ground
    --c-deck                15 20 34        section ground
    --c-pad                 21 27 45        a pad face
    --c-pad-hi              28 36 58        pad hover / selected row
    --c-rim                 40 50 78        pad edge
    --c-ink                 248 250 252     primary text
    --c-ink-muted           148 163 184     body text
    --c-ink-dim             111 126 148     labels and meta
    --c-ink-faint           71 85 105        the quietest marks
    --c-brass               124 58 237      accent, one end of the pair
    --c-brass-lit           34 211 238      accent, the other end
    --c-brass-deep          76 29 149       accent shadow
    --c-accent-far          16 185 129      the ramp's third stop
    --c-live                16 185 129     "bridge is running"
    --c-cold                71 85 105        "not running"

These two are full CSS colours rather than channels:

    --c-line                rgba(148, 163, 184, 0.14)
    --c-line-strong         rgba(148, 163, 184, 0.28)

Shape, rhythm and faces:

    --pad-radius            12px
    --pad-min-width         208px           grid column floor
    --pad-min-width-compact 140px           ditto, compact mode
    --pad-gap               14px
    --font-display-stack    headlines
    --font-mono-stack       labels and chords

## Example: a terminal-green launcher

    :root {
      --c-bg: 4 8 6;
      --c-deck: 7 13 10;
      --c-pad: 10 20 15;
      --c-pad-hi: 14 30 22;
      --c-ink: 210 255 228;
      --c-ink-muted: 130 190 160;
      --c-brass: 80 240 160;
      --c-line: rgba(80, 240, 160, 0.14);
      --pad-radius: 2px;
      --font-display-stack: ui-monospace, monospace;
    }

## Going further than colour

theme.css is ordinary CSS against a live page, so you can restyle anything,
not just the tokens. Useful hooks:

    .pad-grid          the board grid
    .pad-face          a pad clickable face
    .display-hero      the big editorial headline
    .machined-strip    the header band
    .grain::after      the film grain (set display:none to kill it)

For behaviour, create promtly-local/custom.js. It runs on every page the
bridge serves, after the app mounts.

## Ready-made looks

Two are published; fetch one into theme.css and edit from there.

    promtly.dev/themes/terminal.css   green phosphor, square corners, mono
    promtly.dev/themes/brass.css      warm charcoal and brass, serif display
    promtly.dev/themes/neon.css       the second brand kit: green into blue

## Sharing it

Your pads live in the browser - export them from the board Import panel - and
your look lives in theme.css. Those two files together are a setup someone
else can drop in and have exactly what you have.

## What is deliberately not themeable

The safety behaviour. It still verifies the window switch landed before
sending a keystroke, still binds to 127.0.0.1 only, and still answers no
origin but promtly.dev.
`;

const LOCAL_DIR = resolvePath(
  process.env.PROMTLY_LOCAL_DIR || join(dirname(process.argv[1] || "."), "promtly-local"),
);
const THEME_FILE = join(LOCAL_DIR, "theme.css");
const CUSTOM_JS = join(LOCAL_DIR, "custom.js");
const GUIDE_FILE = resolvePath(join(dirname(process.argv[1] || "."), "PROMTLY-CUSTOMIZE.md"));

const THEME_SEED = `/* Your copy of Promtly. Anything you redefine here wins.
 *
 * Every token is listed in PROMTLY-CUSTOMIZE.md next to the bridge script.
 * Colours are space-separated RGB channels, so the app's /opacity modifiers
 * keep working. Save the file and the open window picks it up in about a
 * second - no reload, no rebuild.
 *
 * Try uncommenting this:
 */

/*
:root {
  --c-bg: 6 8 10;
  --c-brass: 120 220 190;
  --c-ink: 224 232 236;
  --pad-radius: 2px;
  --font-display-stack: "Iosevka", ui-monospace, monospace;
}
*/
`;

function ensureLocalDir() {
  try {
    if (!existsSync(LOCAL_DIR)) mkdirSync(LOCAL_DIR, { recursive: true });
    if (!existsSync(THEME_FILE)) writeFileSync(THEME_FILE, THEME_SEED, "utf8");
    // ⚠ Rewrite the guide when it drifts, unlike theme.css which is the
    // user's own file. This doc is what gets handed to a model; a stale token
    // table is worse than no table, because the model styles confidently
    // against defaults that were retired two versions ago.
    let guideOnDisk = "";
    try {
      guideOnDisk = existsSync(GUIDE_FILE) ? readFileSync(GUIDE_FILE, "utf8") : "";
    } catch {
      guideOnDisk = "";
    }
    if (guideOnDisk !== CUSTOMIZE_GUIDE) writeFileSync(GUIDE_FILE, CUSTOMIZE_GUIDE, "utf8");
    return true;
  } catch (err) {
    log(`could not prepare ${LOCAL_DIR}: ${String(err && err.message ? err.message : err)}`);
    return false;
  }
}

function localStamp() {
  const stamp = (file) => {
    try {
      return existsSync(file) ? String(statSync(file).mtimeMs) : "0";
    } catch {
      return "0";
    }
  };
  return `${stamp(THEME_FILE)}-${stamp(CUSTOM_JS)}`;
}

function readLocal(file) {
  try {
    return existsSync(file) ? readFileSync(file, "utf8") : "";
  } catch {
    return "";
  }
}

/**
 * Inject the local layer into the mirrored page.
 *
 * The stylesheet goes LAST in <head> so it outranks the bundle's tokens
 * without needing !important. The watcher swaps only the stylesheet href on
 * change, so a restyle does not reload the page and lose what you were
 * typing.
 */
function injectLocalLayer(html) {
  const version = localStamp();
  const hasCustomJs = existsSync(CUSTOM_JS);
  const tags =
    `
<link id="promtly-local-theme" rel="stylesheet" href="/local/theme.css?v=${version}">` +
    (hasCustomJs ? `
<script src="/local/custom.js?v=${version}" defer></script>` : "") +
    `
<script>(function(){var v=${JSON.stringify(version)};setInterval(function(){` +
    `fetch("/local/version",{cache:"no-store"}).then(function(r){return r.text()}).then(function(n){` +
    `if(n===v)return;v=n;var l=document.getElementById("promtly-local-theme");` +
    `if(l)l.setAttribute("href","/local/theme.css?v="+encodeURIComponent(n));` +
    `else location.reload();}).catch(function(){});},1500);})();</script>
`;

  return html.includes("</head>") ? html.replace("</head>", `${tags}</head>`) : html + tags;
}

// ---------------------------------------------------------------------------
// The window/keyboard half: one long-lived PowerShell host with a P/Invoke
// shim. Spawning a process per keystroke would cost ~300ms and make the
// whole thing feel worse than Ctrl+V by hand.
// ---------------------------------------------------------------------------

const PS_SOURCE = String.raw`
$ErrorActionPreference = 'Stop'
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8

Add-Type -TypeDefinition @"
using System;
using System.Runtime.InteropServices;
using System.Text;

[StructLayout(LayoutKind.Sequential)]
public struct RECT { public int left; public int top; public int right; public int bottom; }

public class PromtlyWin {
  public delegate bool EnumProc(IntPtr hWnd, IntPtr param);

  [DllImport("user32.dll")] public static extern IntPtr GetForegroundWindow();
  [DllImport("user32.dll", SetLastError=true)] public static extern bool SetForegroundWindow(IntPtr hWnd);
  [DllImport("user32.dll")] public static extern bool BringWindowToTop(IntPtr hWnd);
  [DllImport("user32.dll", CharSet=CharSet.Unicode)] public static extern int GetWindowTextW(IntPtr hWnd, StringBuilder lpString, int nMaxCount);
  [DllImport("user32.dll", CharSet=CharSet.Unicode)] public static extern int GetWindowTextLengthW(IntPtr hWnd);
  [DllImport("user32.dll")] public static extern bool IsWindow(IntPtr hWnd);
  [DllImport("user32.dll")] public static extern bool IsWindowVisible(IntPtr hWnd);
  [DllImport("user32.dll")] public static extern bool IsIconic(IntPtr hWnd);
  [DllImport("user32.dll")] public static extern bool ShowWindow(IntPtr hWnd, int nCmdShow);
  [DllImport("user32.dll")] public static extern IntPtr GetWindow(IntPtr hWnd, uint uCmd);
  [DllImport("user32.dll", SetLastError=true)] public static extern int GetWindowLongW(IntPtr hWnd, int nIndex);
  [DllImport("user32.dll")] public static extern IntPtr GetShellWindow();
  [DllImport("user32.dll")] public static extern bool EnumWindows(EnumProc cb, IntPtr param);
  [DllImport("dwmapi.dll")] public static extern int DwmGetWindowAttribute(IntPtr hwnd, int attr, out int val, int size);
  [DllImport("user32.dll")] public static extern void keybd_event(byte bVk, byte bScan, uint dwFlags, UIntPtr dwExtraInfo);
  [DllImport("user32.dll")] public static extern uint GetWindowThreadProcessId(IntPtr hWnd, out uint pid);
  [DllImport("user32.dll")] public static extern bool AttachThreadInput(uint idAttach, uint idAttachTo, bool fAttach);
  [DllImport("kernel32.dll")] public static extern uint GetCurrentThreadId();
  [DllImport("user32.dll", SetLastError=true)] public static extern bool SetWindowPos(IntPtr hWnd, IntPtr after, int x, int y, int cx, int cy, uint flags);
  [DllImport("user32.dll")] public static extern bool GetWindowRect(IntPtr hWnd, out RECT rect);
  [DllImport("user32.dll")] public static extern bool SystemParametersInfoW(uint action, uint param, out RECT data, uint winIni);

  const uint GW_HWNDNEXT = 2;
  const int GWL_EXSTYLE = -20;
  const int WS_EX_TOOLWINDOW = 0x00000080;
  const int WS_EX_NOACTIVATE = 0x08000000;
  const int DWMWA_CLOAKED = 14;
  const int SW_RESTORE = 9;

  // The window a paste should land in, pinned at summon time. Deciding it
  // at summon rather than at paste time is what makes targeting
  // deterministic: "the window behind the foreground" is a guess that
  // breaks the moment the board is a tab among other windows.
  static IntPtr armed = IntPtr.Zero;
  // !! TWO states, not one boolean. "Armed" alone cannot tell a target the
  // user CHOSE (they pressed summon from the window they wanted) from one this
  // process merely guessed and pinned. Submitting is only safe on the former,
  // and conflating them is how a send lands in a window nobody picked.
  static bool bySummon = false;

  // CHAIRS: named windows, so one pad can be driven into several assistants
  // in turn. This is the whole point of the Promtly x Parley merge — seating
  // two models at one table means pasting a briefing into each window, and a
  // local process is the only thing that can do that for you.
  static System.Collections.Generic.Dictionary<string, IntPtr> chairs =
      new System.Collections.Generic.Dictionary<string, IntPtr>(StringComparer.OrdinalIgnoreCase);

  public static string Title(IntPtr h) {
    int len = GetWindowTextLengthW(h);
    if (len <= 0) return "";
    StringBuilder sb = new StringBuilder(len + 2);
    GetWindowTextW(h, sb, sb.Capacity);
    return sb.ToString();
  }

  static bool Cloaked(IntPtr h) {
    int v = 0;
    try { if (DwmGetWindowAttribute(h, DWMWA_CLOAKED, out v, sizeof(int)) == 0) return v != 0; } catch {}
    return false;
  }

  // Windows keeps a great many visible-but-not-real windows around (tool
  // windows, cloaked UWP shells, the desktop). Alt+Tab skips them and so
  // must we, or "the window behind" resolves to a ghost.
  public static bool Eligible(IntPtr h) {
    if (h == IntPtr.Zero) return false;
    if (!IsWindow(h)) return false;
    if (!IsWindowVisible(h)) return false;
    if (h == GetShellWindow()) return false;
    int ex = GetWindowLongW(h, GWL_EXSTYLE);
    if ((ex & WS_EX_TOOLWINDOW) != 0) return false;
    if ((ex & WS_EX_NOACTIVATE) != 0) return false;
    if (Cloaked(h)) return false;
    if (Title(h).Length == 0) return false;
    return true;
  }

  // The window Alt+Tab would land on: walk the Z-order from whatever is in
  // front and take the first eligible window behind it. Used when nothing
  // has been armed.
  /**
   * The window whose title is exactly the wanted string.
   *
   * !! This did not exist, and three verbs called it: F (focus by title), and
   * the two added for window placement. Every one of them came back
   * "does not contain a method named FindByTitle" - which the bridge reported
   * as status "err", and the summon path only opens a new launcher on
   * "notfound". So the chord could never raise an EXISTING launcher window: it
   * armed the target, failed silently, and left the window wherever it was.
   * That is the erratic show/hide behaviour, and it was never the hotkey.
   *
   * Exact match, not a prefix: Chrome titles an --app window with the page
   * title alone, and a prefix match would also catch a tab that happens to
   * start with the same words.
   */
  public static IntPtr FindByTitle(string wanted) {
    IntPtr found = IntPtr.Zero;
    EnumWindows((h, p) => {
      // A minimised window still reports visible, which is what lets the
      // chord restore one it hid a moment ago.
      if (!Eligible(h)) return true;
      if (Title(h) == wanted) { found = h; return false; }
      return true;
    }, IntPtr.Zero);
    return found;
  }

  public static IntPtr Behind() {
    IntPtr fg = GetForegroundWindow();
    IntPtr h = fg;
    for (int i = 0; i < 400 && h != IntPtr.Zero; i++) {
      h = GetWindow(h, GW_HWNDNEXT);
      // !! Never the launcher itself. Nothing stopped this before, so the
      // walk could hand back Promtly's own window and a fired pad would type
      // its prompt into the launcher's search box. It is skipped HERE rather
      // than in Eligible() on purpose: summon has to be able to find the
      // launcher by title in order to focus it.
      if (h != IntPtr.Zero && h != fg && Eligible(h) && Title(h) != "${LAUNCHER_TITLE}") return h;
    }
    return IntPtr.Zero;
  }

  // Window placement. SW_* and HWND_* live here so the verbs below stay short.
  const int SW_MINIMIZE = 6;
  static readonly IntPtr HWND_TOPMOST = new IntPtr(-1);
  static readonly IntPtr HWND_NOTOPMOST = new IntPtr(-2);
  const uint SWP_NOACTIVATE = 0x0010;
  const uint SWP_SHOWWINDOW = 0x0040;

  /** The desktop work area: the screen minus the taskbar. */
  public static RECT WorkArea() {
    RECT r;
    if (SystemParametersInfoW(0x0030, 0, out r, 0)) return r;
    r.left = 0; r.top = 0; r.right = 1920; r.bottom = 1080;
    return r;
  }

  /**
   * Place the launcher.
   *
   * !! The RIGHT edge, always. Every assistant puts its conversation list down
   * the left, so a launcher that opens centred or left covers the thing you
   * were reading. "peek" is a strip parked at the right edge and kept topmost
   * so it survives being behind the window you are typing in; "full" is the
   * real launcher and gives up topmost so it cannot sit over a dialog.
   */
  public static bool Place(IntPtr h, string mode) {
    if (h == IntPtr.Zero || !IsWindow(h)) return false;
    RECT wa = WorkArea();
    int waW = wa.right - wa.left;
    int waH = wa.bottom - wa.top;
    if (mode == "hide") { ShowWindow(h, SW_MINIMIZE); return true; }
    int w = mode == "peek" ? 320 : 560;
    int hh;
    if (mode == "peek") {
      hh = 52;
    } else {
      // Fit the work area on a short screen, but never collapse to a sliver.
      // The clamp is full-mode only: it used to run for peek too and inflated
      // the strip to 240px, which is not a peek.
      hh = waH - 160 < 680 ? waH - 160 : 680;
      if (hh < 240) hh = 240;
    }
    int x = wa.right - w - 28;
    int y = mode == "peek" ? wa.top + 28 : wa.top + 72;
    if (IsIconic(h)) ShowWindow(h, SW_RESTORE);
    IntPtr after = mode == "peek" ? HWND_TOPMOST : HWND_NOTOPMOST;
    // NOACTIVATE for peek: parking the strip must never steal what you are
    // typing into. "full" is allowed to take focus, because you asked for it.
    uint flags = SWP_SHOWWINDOW | (mode == "peek" ? SWP_NOACTIVATE : 0);
    return SetWindowPos(h, after, x, y, w, hh, flags);
  }

  public static void Arm(IntPtr h) { armed = h; bySummon = true; }
  public static void PinGuess(IntPtr h) { armed = h; bySummon = false; }
  public static bool IsArmed() { return armed != IntPtr.Zero && Eligible(armed); }
  public static bool IsBySummon() { return bySummon && IsArmed(); }

  public static IntPtr Target() {
    if (IsArmed()) return armed;
    return Behind();
  }

  public static void Seat(string name, IntPtr h) { chairs[name] = h; }

  public static void Unseat(string name) {
    if (name == "") chairs.Clear();
    else if (chairs.ContainsKey(name)) chairs.Remove(name);
  }

  /** A seated window, or Zero once it has been closed. */
  public static IntPtr Chair(string name) {
    IntPtr h;
    if (!chairs.TryGetValue(name, out h)) return IntPtr.Zero;
    return Eligible(h) ? h : IntPtr.Zero;
  }

  /** One chair per line: name, tab, title, tab, 1 or 0 for alive. */
  public static string ChairList() {
    var sb = new StringBuilder();
    foreach (var pair in chairs) {
      bool alive = Eligible(pair.Value);
      sb.Append(pair.Key).Append((char)9)
        .Append(alive ? Title(pair.Value) : "").Append((char)9)
        .Append(alive ? "1" : "0").Append((char)10);
    }
    return sb.ToString();
  }

  public static bool Focus(IntPtr h) {
    if (h == IntPtr.Zero) return false;
    if (IsIconic(h)) ShowWindow(h, SW_RESTORE);
    uint fgPid;
    uint fgThread = GetWindowThreadProcessId(GetForegroundWindow(), out fgPid);
    uint me = GetCurrentThreadId();
    bool attached = (fgThread != 0 && fgThread != me) && AttachThreadInput(fgThread, me, true);
    BringWindowToTop(h);
    bool ok = SetForegroundWindow(h);
    if (!ok) { ok = SetForegroundWindow(h); }
    if (attached) AttachThreadInput(fgThread, me, false);
    return ok;
  }

  public static bool FocusSettled(IntPtr h, int budgetMs) {
    int waited = 0;
    while (waited < budgetMs) {
      if (GetForegroundWindow() == h) return true;
      System.Threading.Thread.Sleep(15);
      waited += 15;
    }
    return GetForegroundWindow() == h;
  }

  public static void CtrlKey(byte vk) {
    const byte VK_CONTROL = 0x11;
    const uint KEYUP = 0x0002;
    keybd_event(VK_CONTROL, 0, 0, UIntPtr.Zero);
    keybd_event(vk, 0, 0, UIntPtr.Zero);
    keybd_event(vk, 0, KEYUP, UIntPtr.Zero);
    keybd_event(VK_CONTROL, 0, KEYUP, UIntPtr.Zero);
  }

  public static void Tap(byte vk) {
    const uint KEYUP = 0x0002;
    keybd_event(vk, 0, 0, UIntPtr.Zero);
    keybd_event(vk, 0, KEYUP, UIntPtr.Zero);
  }
}
"@

function Decode([string]$b64) {
  if ([string]::IsNullOrEmpty($b64)) { return "" }
  return [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($b64))
}
function Encode([string]$s) {
  if ($null -eq $s) { $s = "" }
  return [System.Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes($s))
}
function SetClip([string]$text) {
  try { Set-Clipboard -Value $text; return $true } catch { }
  try {
    Add-Type -AssemblyName System.Windows.Forms
    [System.Windows.Forms.Clipboard]::SetText($text)
    return $true
  } catch { return $false }
}
function GetClip() {
  try { $v = Get-Clipboard -Raw; if ($null -eq $v) { return "" } else { return $v } } catch { return "" }
}

[Console]::Out.WriteLine("R ready ")
[Console]::Out.Flush()

while ($true) {
  $line = [Console]::In.ReadLine()
  if ($null -eq $line) { break }
  $line = $line.Trim()
  if ($line -eq "") { continue }
  $parts = $line.Split(" ")
  $verb = $parts[0]
  $arg = ""
  if ($parts.Length -gt 1) { $arg = $parts[1] }
  $flag = ""
  if ($parts.Length -gt 2) { $flag = $parts[2] }
  $chair = ""
  if ($parts.Length -gt 3) { $chair = Decode $parts[3] }

  try {
    switch ($verb) {
      "T" {
        # !! Re-pin the guess on EVERY query, but never overwrite a summon.
        #
        # Two failures sit on either side of this. Reporting a target without
        # committing to it let the launcher display one window while the fire
        # re-walked the Z-order into another. Pinning it ONCE was worse in a
        # different way: the label froze on whatever happened to be in front
        # when the launcher first opened, so firing an hour later sent text to
        # a window the person had long since left. A guess is re-taken each
        # time and stays truthful; a window you chose with the chord is sticky
        # until you choose another.
        if ([PromtlyWin]::IsBySummon()) {
          $h = [PromtlyWin]::Target()
        } else {
          # Behind() walks from whatever is in FRONT at this instant, so it
          # legitimately finds nothing sometimes. Keep the last good pin in
          # that case rather than blanking the label - a target that flickers
          # to empty reads as the bridge losing track of your window.
          $b = [PromtlyWin]::Behind()
          if ($b -ne [IntPtr]::Zero) {
            [PromtlyWin]::PinGuess($b)
            $h = $b
          } else {
            $h = [PromtlyWin]::Target()
          }
        }
        # Reported flag means CHOSEN, not merely pinned - the launcher uses it
        # to say whether it is confident about the target.
        $armed = if ([PromtlyWin]::IsBySummon()) { "1" } else { "0" }
        [Console]::Out.WriteLine("T ok " + (Encode ([PromtlyWin]::Title($h))) + " " + $armed)
      }
      "A" {
        # Arm BEFORE the launcher is shown, or the launcher itself becomes
        # the remembered target.
        #
        # !! And REFUSE the launcher outright. Arming before showing is not
        # enough on its own: restoring a hidden launcher leaves it frontmost
        # already, and the chord then armed "Promtly Launcher" as the paste
        # target - so the next fire typed the prompt into its own search box.
        # Keeping the previous target is always the better answer, because the
        # window you actually want is the one you were in before.
        $h = [PromtlyWin]::GetForegroundWindow()
        if ($h -ne [IntPtr]::Zero -and [PromtlyWin]::Title($h) -eq "${LAUNCHER_TITLE}") {
          [Console]::Out.WriteLine("A kept " + (Encode ([PromtlyWin]::Title([PromtlyWin]::Target()))))
        } else {
          [PromtlyWin]::Arm($h)
          [Console]::Out.WriteLine("A ok " + (Encode ([PromtlyWin]::Title($h))))
        }
      }
      "F" {
        $h = [PromtlyWin]::FindByTitle((Decode $arg))
        if ($h -eq [IntPtr]::Zero) {
          [Console]::Out.WriteLine("F notfound " + (Encode ""))
        } else {
          [void][PromtlyWin]::Focus($h)
          $ok = [PromtlyWin]::FocusSettled($h, 600)
          [Console]::Out.WriteLine("F " + $(if ($ok) { "ok" } else { "nofocus" }) + " " + (Encode ([PromtlyWin]::Title($h))))
        }
      }
      "H" {
        # Seat the current foreground window under a name.
        $h = [PromtlyWin]::GetForegroundWindow()
        [PromtlyWin]::Seat((Decode $arg), $h)
        [Console]::Out.WriteLine("H ok " + (Encode ([PromtlyWin]::Title($h))))
      }
      "L" {
        [Console]::Out.WriteLine("L ok " + (Encode ([PromtlyWin]::ChairList())))
      }
      "U" {
        [PromtlyWin]::Unseat((Decode $arg))
        [Console]::Out.WriteLine("U ok ")
      }
      "W" {
        # Place the launcher. arg is peek | full | hide.
        $h = [PromtlyWin]::FindByTitle("${LAUNCHER_TITLE}")
        if ($h -eq [IntPtr]::Zero) {
          [Console]::Out.WriteLine("W notfound " + (Encode ""))
        } else {
          $ok = [PromtlyWin]::Place($h, (Decode $arg))
          if ((Decode $arg) -eq "full") {
            [void][PromtlyWin]::Focus($h)
          }
          [Console]::Out.WriteLine("W " + $(if ($ok) { "ok" } else { "failed" }) + " " + (Encode ([PromtlyWin]::Title($h))))
        }
      }
      "G" {
        # Is the launcher the window in front right now?
        $h = [PromtlyWin]::FindByTitle("${LAUNCHER_TITLE}")
        $fg = [PromtlyWin]::GetForegroundWindow()
        # !! A MINIMISED window is never "in front", and IntPtr -eq in
        # PowerShell is not a comparison to trust - compare the values. Without
        # the IsIconic guard the chord read the launcher it had just hidden as
        # still frontmost and hid it again, so it could minimise but never
        # restore.
        $front = if (
          $h -ne [IntPtr]::Zero -and
          -not [PromtlyWin]::IsIconic($h) -and
          $h.ToInt64() -eq $fg.ToInt64()
        ) { "1" } else { "0" }
        $exists = if ($h -ne [IntPtr]::Zero) { "1" } else { "0" }
        [Console]::Out.WriteLine("G ok " + (Encode $exists) + " " + $front)
      }
      "D" {
        # Hand the foreground back to whatever was armed, without typing.
        $target = [PromtlyWin]::Target()
        if ($target -eq [IntPtr]::Zero) {
          [Console]::Out.WriteLine("D notarget " + (Encode ""))
        } else {
          [void][PromtlyWin]::Focus($target)
          $ok = [PromtlyWin]::FocusSettled($target, 400)
          [Console]::Out.WriteLine("D " + $(if ($ok) { "ok" } else { "nofocus" }) + " " + (Encode ([PromtlyWin]::Title($target))))
        }
      }
      "S" {
        # Copy whatever is selected in the foreground window. The selection
        # is only reachable by asking that window for it.
        [PromtlyWin]::CtrlKey(0x43)
        Start-Sleep -Milliseconds 140
        [Console]::Out.WriteLine("S ok " + (Encode (GetClip)))
      }
      "C" {
        $ok = SetClip (Decode $arg)
        if ($ok) { [Console]::Out.WriteLine("C ok ") } else { [Console]::Out.WriteLine("C clipfail ") }
      }
      "P" {
        if ($chair -ne "") { $target = [PromtlyWin]::Chair($chair) }
        else { $target = [PromtlyWin]::Target() }
        $title = [PromtlyWin]::Title($target)
        # !! There is deliberately NO "refuse to submit unless summoned" guard
        # here, and it was tried: it made clicking a send-pad copy the text and
        # do nothing else, which is indistinguishable from the tool being
        # broken. The target is PINNED and shown in the launcher before you
        # fire it, so firing at the named window is a choice, not a guess.
        if (-not (SetClip (Decode $arg))) {
          [Console]::Out.WriteLine("P clipfail " + (Encode $title))
        } elseif ($target -eq [IntPtr]::Zero) {
          [Console]::Out.WriteLine("P notarget " + (Encode ""))
        } else {
          [void][PromtlyWin]::Focus($target)
          if ([PromtlyWin]::FocusSettled($target, 450)) {
            Start-Sleep -Milliseconds 40
            [PromtlyWin]::CtrlKey(0x56)
            if ($flag -eq "1") {
              # Submit. Deliberately after a pause: a chat box that has just
              # received a paste is often still resizing its input.
              Start-Sleep -Milliseconds 120
              [PromtlyWin]::Tap(0x0D)
            }
            [Console]::Out.WriteLine("P ok " + (Encode $title))
          } else {
            # Focus refused. Sending Ctrl+V now would paste into whatever is
            # still in front. Report it and let the page say so.
            [Console]::Out.WriteLine("P nofocus " + (Encode $title))
          }
        }
      }
      default { [Console]::Out.WriteLine("? err ") }
    }
  } catch {
    [Console]::Out.WriteLine($verb + " err " + (Encode $_.Exception.Message))
  }
  [Console]::Out.Flush()
}
`;

// A second, dedicated host for global hotkeys. It has to block on a
// message loop, which the command host above cannot do while it is
// blocking on stdin — hence two processes rather than one.
//
// RegisterHotKey with a NULL window posts WM_HOTKEY to the calling
// THREAD's queue, so no window is needed; GetMessage picks it up.
const PS_HOTKEYS = String.raw`
$ErrorActionPreference = 'Stop'
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8

Add-Type -TypeDefinition @"
using System;
using System.Runtime.InteropServices;

public class PromtlyKeys {
  [StructLayout(LayoutKind.Sequential)]
  public struct MSG {
    public IntPtr hwnd; public uint message; public IntPtr wParam; public IntPtr lParam;
    public uint time; public int ptX; public int ptY;
  }

  [DllImport("user32.dll")] static extern bool RegisterHotKey(IntPtr hWnd, int id, uint fsModifiers, uint vk);
  [DllImport("user32.dll")] static extern int GetMessage(out MSG lpMsg, IntPtr hWnd, uint min, uint max);

  const uint MOD_ALT = 0x0001, MOD_CONTROL = 0x0002, MOD_SHIFT = 0x0004, MOD_NOREPEAT = 0x4000;
  const uint WM_HOTKEY = 0x0312;

  struct Chord { public uint mods; public byte vk; public string label; }

  static Chord C(uint mods, byte vk, string label) {
    Chord c; c.mods = mods; c.vk = vk; c.label = label; return c;
  }

  // ⚠ A global chord can already be owned by another app, and
  // RegisterHotKey simply returns false — on this machine Ctrl+Alt+Space
  // was already taken. So each action has a list of candidates and the
  // first one that registers wins; the label is reported back so the UI
  // can show the chord that actually works rather than the one we wanted.
  static string Claim(int id, Chord[] candidates) {
    for (int i = 0; i < candidates.Length; i++) {
      if (RegisterHotKey(IntPtr.Zero, id, candidates[i].mods | MOD_NOREPEAT, candidates[i].vk)) {
        return candidates[i].label;
      }
    }
    return "";
  }

  public static void Listen() {
    Chord[] summon = new Chord[] {
      C(MOD_CONTROL | MOD_ALT, 0x20, "Ctrl+Alt+Space"),
      C(MOD_CONTROL | MOD_SHIFT, 0x20, "Ctrl+Shift+Space"),
      C(MOD_CONTROL | MOD_ALT, 0x4A, "Ctrl+Alt+J"),
      C(MOD_CONTROL | MOD_ALT, 0x51, "Ctrl+Alt+Q")
    };
    Chord[] capture = new Chord[] {
      C(MOD_CONTROL | MOD_ALT, 0x43, "Ctrl+Alt+C"),
      C(MOD_CONTROL | MOD_ALT, 0x58, "Ctrl+Alt+X"),
      C(MOD_CONTROL | MOD_ALT, 0x4B, "Ctrl+Alt+K")
    };
    string s = Claim(1, summon);
    string c = Claim(2, capture);
    Console.Out.WriteLine("K ready " + (s == "" ? "-" : s) + "|" + (c == "" ? "-" : c));
    Console.Out.Flush();
    MSG m;
    while (GetMessage(out m, IntPtr.Zero, 0, 0) > 0) {
      if (m.message == WM_HOTKEY) {
        Console.Out.WriteLine("K hot " + m.wParam.ToInt32());
        Console.Out.Flush();
      }
    }
  }
}
"@

[PromtlyKeys]::Listen()
`;

function spawnPowerShell(source, name) {
  const dir = mkdtempSync(join(tmpdir(), "promtly-"));
  const scriptPath = join(dir, `${name}.ps1`);
  writeFileSync(scriptPath, source, "utf8");
  return spawn(
    "powershell.exe",
    [
      "-NoProfile",
      "-NonInteractive",
      "-ExecutionPolicy",
      "Bypass",
      "-STA",
      "-File",
      scriptPath,
    ],
    { stdio: ["pipe", "pipe", "pipe"], windowsHide: true },
  );
}

class WindowsDriver {
  constructor() {
    /** @type {{resolve:(v:{status:string,title:string,extra:string})=>void, reject:(e:Error)=>void}[]} */
    this.queue = [];
    this.buffer = "";
    this.proc = null;
    this.ready = false;
    this.lastError = null;
  }

  start() {
    this.proc = spawnPowerShell(PS_SOURCE, "promtly-win");
    this.proc.stdout.setEncoding("utf8");
    this.proc.stdout.on("data", (chunk) => this.onData(chunk));
    this.proc.stderr.setEncoding("utf8");
    this.proc.stderr.on("data", (chunk) => {
      this.lastError = String(chunk).trim().slice(0, 400);
    });
    this.proc.on("exit", (code) => {
      this.proc = null;
      this.ready = false;
      const pending = this.queue.splice(0);
      for (const p of pending) p.reject(new Error(`helper exited (${code})`));
    });
  }

  onData(chunk) {
    this.buffer += chunk;
    let index = this.buffer.indexOf("\n");
    while (index !== -1) {
      const line = this.buffer.slice(0, index).trim();
      this.buffer = this.buffer.slice(index + 1);
      if (line) this.handleLine(line);
      index = this.buffer.indexOf("\n");
    }
  }

  handleLine(line) {
    // The helper announces itself once, before any request. Consuming that
    // banner as a reply would desynchronise the whole queue.
    if (line.startsWith("R ")) {
      this.ready = true;
      return;
    }
    const pending = this.queue.shift();
    if (!pending) return;
    const parts = line.split(" ");
    const status = parts[1] || "err";
    const title = parts[2] ? Buffer.from(parts[2], "base64").toString("utf8") : "";
    pending.resolve({ status, title, extra: parts[3] || "" });
  }

  /** @returns {Promise<{status:string,title:string,extra:string}>} */
  send(verb, payload = "", flag = "", chair = "") {
    if (!this.proc) this.start();
    const encoded = payload ? Buffer.from(payload, "utf8").toString("base64") : "";
    const chairArg = chair ? Buffer.from(chair, "utf8").toString("base64") : "";
    return new Promise((resolve, reject) => {
      const entry = {
        resolve: (value) => {
          clearTimeout(timer);
          resolve(value);
        },
        reject: (err) => {
          clearTimeout(timer);
          reject(err);
        },
      };
      const timer = setTimeout(() => {
        const at = this.queue.indexOf(entry);
        if (at !== -1) this.queue.splice(at, 1);
        reject(new Error("helper timed out"));
      }, 8000);
      this.queue.push(entry);
      this.proc.stdin.write(
        `${verb} ${encoded} ${flag || "0"} ${chairArg}\n`.replace(/ +\n$/, "\n"),
      );
    });
  }

  target() {
    return this.send("T");
  }
  arm() {
    return this.send("A");
  }
  focusTitle(title) {
    return this.send("F", title);
  }
  grabSelection() {
    return this.send("S");
  }
  copy(text) {
    return this.send("C", text);
  }
  paste(text, submit, chair = "") {
    return this.send("P", text, submit ? "1" : "0", chair);
  }
  seat(name) {
    return this.send("H", name);
  }
  chairs() {
    return this.send("L");
  }
  unseat(name) {
    return this.send("U", name);
  }
  /** Place the launcher: "peek" | "full" | "hide". */
  place(mode) {
    return this.send("W", mode);
  }

  /** {exists, front} for the launcher window. */
  async launcherState() {
    const reply = await this.send("G");
    return { exists: reply.title === "1", front: reply.extra === "1" };
  }

  dismiss() {
    return this.send("D");
  }
}

// ---------------------------------------------------------------------------
// Hotkeys
// ---------------------------------------------------------------------------

/** @type {{id:string, text:string, at:number}[]} */
const captures = [];

function findBrowser() {
  const candidates = [
    "C:/Program Files/Google/Chrome/Application/chrome.exe",
    "C:/Program Files (x86)/Google/Chrome/Application/chrome.exe",
    join(homedir(), "AppData/Local/Google/Chrome/Application/chrome.exe"),
    "C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe",
    "C:/Program Files/Microsoft/Edge/Application/msedge.exe",
  ];
  return candidates.find((p) => existsSync(p)) || null;
}

function openLauncherWindow() {
  const exe = findBrowser();
  if (!exe) {
    log("no Chrome or Edge found — open http://127.0.0.1:" + PORT + "/launch yourself.");
    return false;
  }
  // An --app window is a real OS window with its own title and no browser
  // chrome, which is what makes "summon" feel like a launcher rather than a
  // tab hunt.
  const child = spawn(
    exe,
    [`--app=http://127.0.0.1:${PORT}/launch`, "--window-size=560,680"],
    { detached: true, stdio: "ignore" },
  );
  child.unref();
  // !! Then MOVE it. Chrome's --window-position is measured from the primary
  // display's origin and knows nothing about the taskbar, so the bridge places
  // the window itself once it exists - right edge, inside the work area. Every
  // assistant keeps its conversation list down the left, and a launcher that
  // opens centred covers the thing you were reading.
  //
  // Polled rather than awaited: Chrome forks, and the window does not exist
  // when spawn() returns. Six tries at 400ms covers a cold start without
  // leaving a timer running if the window never appears.
  if (driver) {
    let tries = 0;
    const settle = setInterval(() => {
      tries += 1;
      driver
        .place("full")
        .then((reply) => {
          if (reply.status === "ok" || tries >= 6) clearInterval(settle);
        })
        .catch(() => {
          if (tries >= 6) clearInterval(settle);
        });
    }, 400);
  }
  return true;
}

class HotkeyHost {
  constructor(onHotkey) {
    this.onHotkey = onHotkey;
    this.proc = null;
    this.buffer = "";
    this.registered = null;
  }

  start() {
    this.proc = spawnPowerShell(PS_HOTKEYS, "promtly-keys");
    this.proc.stdout.setEncoding("utf8");
    this.proc.stdout.on("data", (chunk) => {
      this.buffer += chunk;
      let index = this.buffer.indexOf("\n");
      while (index !== -1) {
        const line = this.buffer.slice(0, index).trim();
        this.buffer = this.buffer.slice(index + 1);
        if (line.startsWith("K ready")) {
          const [summon, capture] = line.slice("K ready".length).trim().split("|");
          this.registered = {
            summon: summon && summon !== "-" ? summon : null,
            capture: capture && capture !== "-" ? capture : null,
          };
          log("");
          log(
            this.registered.summon
              ? `  ${this.registered.summon.padEnd(16)} summon the launcher over whatever you are in`
              : "  (no chord free)    summon hotkey unavailable — every candidate is taken",
          );
          log(
            this.registered.capture
              ? `  ${this.registered.capture.padEnd(16)} turn the current selection into a new pad`
              : "  (no chord free)    capture hotkey unavailable — every candidate is taken",
          );
          log("");
        } else if (line.startsWith("K hot")) {
          const id = Number(line.split(" ")[2]);
          if (id) void this.onHotkey(id);
        }
        index = this.buffer.indexOf("\n");
      }
    });
    this.proc.on("exit", (code) => {
      this.proc = null;
      log(`hotkey host exited (${code}); global shortcuts are off.`);
    });
  }
}

const supported = process.platform === "win32";

// ---------------------------------------------------------------------------
// Start with Windows.
//
// The difference between a demo and something you use every day is whether it
// is running when you reach for it. This writes one .cmd into the Startup
// folder and nothing else — no service, no registry, no elevation — and
// --uninstall-startup takes it back out. Opt-in only: a tool that adds itself
// to startup uninvited has made a decision that was not its to make.
// ---------------------------------------------------------------------------

/** A Start Menu entry, so the bridge can be started without a terminal. */
function startMenuShortcutPath() {
  return join(
    homedir(),
    "AppData/Roaming/Microsoft/Windows/Start Menu/Programs/Promtly.cmd",
  );
}

function startupShortcutPath() {
  return join(
    homedir(),
    "AppData/Roaming/Microsoft/Windows/Start Menu/Programs/Startup/promtly-bridge.cmd",
  );
}

/** Is the sign-in entry there right now? The toggle in the UI reads this. */
function startupInstalled() {
  try {
    return existsSync(startupShortcutPath());
  } catch {
    return false;
  }
}

function manageStartup(action) {
  if (process.platform !== "win32") {
    console.error("start-with-Windows is Windows-only.");
    return 1;
  }
  const target = startupShortcutPath();
  try {
    if (action === "install") {
      const script = resolvePath(process.argv[1]);
      mkdirSync(dirname(target), { recursive: true });
      writeFileSync(
        target,
        [
          "@echo off",
          "REM Starts the Promtly bridge at sign-in. Delete this file to stop.",
          `cd /d "${dirname(script)}"`,
          // ⚠ A startup task that fails silently is worse than no startup
          // task: you reach for the chord, nothing happens, and there is
          // nothing to read. If node is not on PATH at sign-in, say so in a
          // log next to the script rather than vanishing.
          "where node >nul 2>nul",
          "if errorlevel 1 (",
          // ⚠ TEMP, not next to the script: when the bridge lives inside a
          // web root (it does in this repo) a log beside it would be a
          // publicly served file.
          `  echo [%DATE% %TIME%] node is not on PATH at sign-in; bridge not started. >> "${join(tmpdir(), "promtly-startup.log")}"`,
          "  exit /b 1",
          ")",
          // The launcher window OPENS at sign-in, deliberately.
          //
          // This used to pass --no-open, on the reasoning that a window
          // appearing at boot is rude. In practice it made the tool invisible:
          // the bridge was running, but the summon chord had no window to
          // focus and nothing appeared to be installed at all. A launcher you
          // have to discover is worse than one that shows itself once.
          `start "" /min node "${script}"`,
          "",
        ].join(EOL),
        "utf8",
      );
      // Searchable as "Promtly" in the Start menu, so the bridge can be
      // started again without a terminal. A .cmd rather than a .lnk because a
      // shortcut needs COM, and this has to work from a plain node process
      // with no dependencies.
      const menu = startMenuShortcutPath();
      mkdirSync(dirname(menu), { recursive: true });
      writeFileSync(
        menu,
        [
          "@echo off",
          "REM Starts Promtly and opens the launcher.",
          `cd /d "${dirname(script)}"`,
          `start "" /min node "${script}"`,
          "",
        ].join(EOL),
        "utf8",
      );
      console.log(`Promtly will start with Windows.
  ${target}
  ${menu}
  (also in the Start menu as "Promtly")`);
    } else {
      try {
        rmSync(startMenuShortcutPath(), { force: true });
      } catch {
        /* the Start Menu entry may never have been written */
      }
      if (existsSync(target)) {
        rmSync(target);
        console.log(`Removed.
  ${target}`);
      } else {
        console.log("It was not installed.");
      }
    }
    return 0;
  } catch (err) {
    console.error(`Could not update startup: ${String(err && err.message ? err.message : err)}`);
    return 1;
  }
}

// ---------------------------------------------------------------------------
// Staying current.
//
// ⭐ Two halves update differently, and only one of them needed building.
//
// The BOARD is mirrored from promtly.dev with a 60-second freshness window and
// background revalidation, so a deploy reaches every running bridge within one
// open. Nobody has to do anything; there is no version of the app to be on.
//
// This FILE is the half that does not: it was downloaded once and would sit at
// whatever version it was fetched at forever. So it asks upstream what the
// current version is, reports it in /health, and installs on request.
//
// ⚠ CHECK-AND-OFFER, NEVER SILENT. This is executable code on someone's
// machine; replacing it without being asked is a different trust relationship
// than the one they agreed to when they downloaded it once. The UI shows a
// badge, the person clicks it, and the swap needs a restart they perform.
// ---------------------------------------------------------------------------

/** Latest version seen upstream, and when we last looked. */
let upstreamVersion = null;
let upstreamCheckedAt = 0;
const UPDATE_CHECK_MS = 6 * 60 * 60 * 1000;

/** The URL this script came from, and would be replaced from. */
const SELF_URL = `${UPSTREAM}/bridge/promtly-bridge.mjs`;

function parseVersion(text) {
  const m = /const VERSION = "([0-9]+\.[0-9]+\.[0-9]+)"/.exec(text);
  return m ? m[1] : null;
}

/** -1 / 0 / 1, comparing dotted numeric versions. */
function compareVersions(a, b) {
  const pa = a.split(".").map(Number);
  const pb = b.split(".").map(Number);
  for (let i = 0; i < 3; i++) {
    if ((pa[i] || 0) !== (pb[i] || 0)) return (pa[i] || 0) < (pb[i] || 0) ? -1 : 1;
  }
  return 0;
}

/**
 * ⛔ Refuse to overwrite a bridge that lives inside a git checkout.
 *
 * On the machine this was WRITTEN on, the running script IS the repository's
 * source file (public/bridge/promtly-bridge.mjs). A self-update
 * there would silently overwrite uncommitted work with the deployed build and
 * look like a git catastrophe rather than an update. A downloaded copy sits in
 * a plain folder and has no .git above it.
 */
function isDevelopmentCopy() {
  try {
    let dir = dirname(resolvePath(process.argv[1]));
    for (let i = 0; i < 12; i++) {
      if (existsSync(join(dir, ".git"))) return true;
      const up = dirname(dir);
      if (up === dir) break;
      dir = up;
    }
  } catch {
    /* if we cannot tell, fall through to the safe answer below */
  }
  return false;
}

async function checkForUpdate(force = false) {
  if (!force && Date.now() - upstreamCheckedAt < UPDATE_CHECK_MS) return upstreamVersion;
  upstreamCheckedAt = Date.now();
  try {
    const res = await fetch(SELF_URL, { cache: "no-store" });
    if (!res.ok) return upstreamVersion;
    const found = parseVersion(await res.text());
    if (found) upstreamVersion = found;
  } catch {
    // Offline is not an error worth shouting about; the bridge works offline
    // on purpose and this is the one thing that needs the network.
  }
  return upstreamVersion;
}

function updateAvailable() {
  return Boolean(upstreamVersion && compareVersions(VERSION, upstreamVersion) < 0);
}

/**
 * Fetch the current bridge and write it over this file.
 *
 * The previous version is kept beside it as .bak rather than discarded: the
 * one failure mode that matters is downloading something that does not run,
 * and leaving no way back from a launcher that no longer starts.
 */
async function installUpdate() {
  if (isDevelopmentCopy()) {
    return { ok: false, error: "this bridge is inside a git checkout - update it with git, not from here" };
  }
  let text;
  try {
    const res = await fetch(SELF_URL, { cache: "no-store" });
    if (!res.ok) return { ok: false, error: `upstream returned ${res.status}` };
    text = await res.text();
  } catch (err) {
    return { ok: false, error: `could not reach ${UPSTREAM}` };
  }
  const found = parseVersion(text);
  // Sanity, not trust: this came from the same origin over https as the
  // original download. The checks catch a truncated transfer or a proxy's
  // error page, which is what actually happens.
  if (!found || text.length < 20_000 || !text.includes("promtly")) {
    return { ok: false, error: "what came back is not a bridge" };
  }
  if (compareVersions(VERSION, found) >= 0) {
    return { ok: true, version: VERSION, already: true };
  }
  try {
    const self = resolvePath(process.argv[1]);
    writeFileSync(`${self}.bak`, readFileSync(self));
    writeFileSync(self, text, "utf8");
    upstreamVersion = found;
    log(`updated to ${found} on disk - restart the bridge to run it.`);
    return { ok: true, version: found, restartRequired: true };
  } catch (err) {
    return { ok: false, error: String(err && err.message ? err.message : err) };
  }
}

const argv = process.argv.slice(2);
if (argv.includes("--install-startup")) process.exit(manageStartup("install"));
if (argv.includes("--uninstall-startup")) process.exit(manageStartup("uninstall"));

const driver = supported ? new WindowsDriver() : null;
if (driver) driver.start();

let lastArmed = "";

async function handleHotkey(id) {
  if (!driver) return;
  try {
    if (id === 1) {
      // Summon. Arm first — the launcher must not become its own target.
      // !! SUMMON ONLY - no hide-on-second-press, deliberately.
      //
      // A toggle was built here and taken out. It worked in isolation
      // (SHOWN/HIDDEN alternating on the chord) but its "is the launcher in
      // front?" test is only correct when the launcher is genuinely
      // foreground, and anything else holding focus - which is normal, since
      // you press this chord FROM another window - made it show when it should
      // hide and arm the wrong target on the way. A launcher that sometimes
      // vanishes when you summon it is worse than one that never hides.
      //
      // Escape in the launcher already dismisses it and hands focus back.
      const armed = await driver.arm();
      lastArmed = armed.title;
      log(`summon: target armed as "${armed.title || "(none)"}"`);
      const found = await driver.focusTitle(LAUNCHER_TITLE);
      if (found.status === "notfound") {
        openLauncherWindow();
        return;
      }
      // Now that FindByTitle exists, this actually raises the window it found
      // and parks it on the right edge.
      await driver.place("full");
      return;
    }
    if (id === 2) {
      const grabbed = await driver.grabSelection();
      const text = (grabbed.title || "").trim();
      if (!text) {
        log("capture: nothing was selected.");
        return;
      }
      captures.push({
        id: `cap_${Date.now().toString(36)}${Math.random().toString(36).slice(2, 6)}`,
        text,
        at: Date.now(),
      });
      log(`capture: ${text.length} chars held for the board (${captures.length} waiting)`);
    }
  } catch (err) {
    log(`hotkey ${id} failed: ${String(err && err.message ? err.message : err)}`);
  }
}

const hotkeys = supported ? new HotkeyHost(handleHotkey) : null;
if (hotkeys) hotkeys.start();

// ---------------------------------------------------------------------------
// HTTP. Loopback only, and an Origin allowlist — a browser cannot forge
// Origin from script, so a hostile page cannot reach this even though the
// port is open.
// ---------------------------------------------------------------------------

function corsHeaders(origin) {
  return {
    "Access-Control-Allow-Origin": origin,
    "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
    "Access-Control-Allow-Headers": "content-type",
    "Access-Control-Max-Age": "600",
    // Load-bearing for the hosted board: Chrome gates public-to-loopback
    // behind Private Network Access and blocks the real request unless the
    // preflight grants it. Necessary but NOT sufficient — see the mirror.
    "Access-Control-Allow-Private-Network": "true",
    Vary: "Origin",
  };
}

function send(res, status, body, origin) {
  res.writeHead(status, {
    "Content-Type": "application/json; charset=utf-8",
    "Cache-Control": "no-store",
    ...(origin ? corsHeaders(origin) : {}),
  });
  res.end(JSON.stringify(body));
}

function readJson(req) {
  return new Promise((resolve, reject) => {
    let raw = "";
    let size = 0;
    req.on("data", (chunk) => {
      size += chunk.length;
      // A prompt is text. Anything past this is not a prompt.
      if (size > 1000000) {
        reject(new Error("payload too large"));
        req.destroy();
        return;
      }
      raw += chunk;
    });
    req.on("end", () => {
      try {
        resolve(raw ? JSON.parse(raw) : {});
      } catch (err) {
        reject(err);
      }
    });
    req.on("error", reject);
  });
}

function log(line) {
  const stamp = new Date().toTimeString().slice(0, 8);
  process.stdout.write(`[${stamp}] ${line}\n`);
}

// ---------------------------------------------------------------------------
// The mirror cache.
//
// ⭐ Without this the bridge refetched promtly.dev for EVERY asset on EVERY
// launcher open, with Cache-Control: no-store — so summoning the launcher
// re-downloaded the whole app, and with no connection it did not open at all.
// A local launcher that needs the internet to show you your own prompts is
// the wrong shape.
//
// Stale-while-revalidate: a cached response is served immediately and, if it
// is past FRESH_MS, revalidated in the background with If-None-Match so a
// deploy still lands within one open. If upstream fails and anything is
// cached, the cache wins — that is the offline case, and it is deliberate.
//
// HTML is cached RAW and the local theme/script layer is injected at serve
// time, so a cached page can never bake in a stale layer.
// ---------------------------------------------------------------------------

const CACHE_DIR = join(LOCAL_DIR, "cache");
/** Past this, a hit is still served but revalidated behind the response. */
const FRESH_MS = 60_000;
/** Bodies larger than this are streamed through and not stored. */
const CACHE_MAX_BYTES = 8 * 1024 * 1024;

/** Revalidations in flight, so a burst of hits cannot stack up fetches. */
const revalidating = new Set();

/**
 * Drop cache entries nothing has asked for in a fortnight.
 *
 * The mirrored site is a few dozen stable files, so this is not about size -
 * it is about renames. Next.js fingerprints its chunks, so every deploy
 * retires a filename permanently, and without a sweep those dead entries sit
 * on disk forever. Runs once at start: the cost is a directory listing, and
 * doing it on a timer would be machinery for a problem that moves this slowly.
 */
function pruneCache() {
  const MAX_AGE_MS = 14 * 24 * 60 * 60 * 1000;
  try {
    if (!existsSync(CACHE_DIR)) return;
    const now = Date.now();
    let dropped = 0;
    for (const name of readdirSync(CACHE_DIR)) {
      const file = join(CACHE_DIR, name);
      try {
        if (now - statSync(file).mtimeMs > MAX_AGE_MS) {
          rmSync(file, { force: true });
          dropped++;
        }
      } catch {
        /* a file that vanished mid-sweep needs no handling */
      }
    }
    if (dropped) log(`cache: dropped ${dropped} stale file(s)`);
  } catch {
    /* pruning is housekeeping; never let it stop the bridge starting */
  }
}

function cacheKey(pathname, search) {
  return createHash("sha1").update(pathname + search).digest("hex");
}

function cachePaths(key) {
  return { body: join(CACHE_DIR, key + ".bin"), meta: join(CACHE_DIR, key + ".json") };
}

function cacheRead(key) {
  const { body, meta } = cachePaths(key);
  try {
    if (!existsSync(body) || !existsSync(meta)) return null;
    const head = JSON.parse(readFileSync(meta, "utf8"));
    return { head, body: readFileSync(body) };
  } catch {
    // A half-written or hand-edited entry is a miss, never a crash.
    return null;
  }
}

function cacheWrite(key, head, body) {
  if (body.length > CACHE_MAX_BYTES) return;
  try {
    if (!existsSync(CACHE_DIR)) mkdirSync(CACHE_DIR, { recursive: true });
    const paths = cachePaths(key);
    // Body first: a reader requires BOTH files, so writing the body before the
    // meta means an interrupted write reads as a miss rather than as a hit
    // with a truncated body.
    writeFileSync(paths.body, body);
    writeFileSync(paths.meta, JSON.stringify(head), "utf8");
  } catch {
    /* a cache that cannot write is just a slower bridge */
  }
}

/** Fetch from upstream and store. Returns {head, body} or null. */
async function fetchUpstream(pathname, search, etag) {
  const headers = {
    accept: "*/*",
    "accept-encoding": "identity",
    "user-agent": `promtly-bridge/${VERSION}`,
  };
  if (etag) headers["if-none-match"] = etag;
  const upstream = await fetch(`${UPSTREAM}${pathname}${search}`, {
    method: "GET",
    headers,
    redirect: "follow",
  });
  if (upstream.status === 304) return "unchanged";
  const body = Buffer.from(await upstream.arrayBuffer());
  const head = {
    status: upstream.status,
    type: upstream.headers.get("content-type") || "application/octet-stream",
    etag: upstream.headers.get("etag") || "",
    storedAt: Date.now(),
  };
  if (upstream.status === 200) cacheWrite(cacheKey(pathname, search), head, body);
  return { head, body };
}

function serveMirrored(res, head, body, isHead) {
  const isHtml = head.type.includes("text/html");
  const payload = isHtml ? Buffer.from(injectLocalLayer(body.toString("utf8"))) : body;
  const headers = {
    "content-type": head.type,
    // The BROWSER still must not cache: the bridge is the cache, and it is the
    // only layer that can tell a deploy from a stale page.
    "cache-control": "no-store",
    "content-length": String(payload.length),
  };
  res.writeHead(head.status, headers);
  res.end(isHead ? undefined : payload);
}

/**
 * Serve the board from this process, mirrored from promtly.dev.
 *
 * ⭐ Not a convenience. A page on https://promtly.dev asking
 * http://127.0.0.1 for something is a public-to-loopback request, and a
 * gated one hangs silently — measured 2026-09-17: the bridge answered curl
 * in 2 ms while the same request from the deployed board never completed.
 * Served from here the board is SAME-ORIGIN with the bridge, so there is
 * nothing to permit. It is still the deployed site; this only re-serves it
 * down loopback, through the cache above — so it opens instantly and works
 * offline, and a deploy lands on the revalidation behind the next open.
 */
async function proxyUpstream(req, res, url) {
  if (req.method !== "GET" && req.method !== "HEAD") {
    send(res, 405, { ok: false, error: "method not allowed" }, undefined);
    return;
  }

  const isHead = req.method === "HEAD";
  const key = cacheKey(url.pathname, url.search);
  const hit = cacheRead(key);

  if (hit) {
    serveMirrored(res, hit.head, hit.body, isHead);
    // Behind the response, never in front of it.
    if (Date.now() - (hit.head.storedAt || 0) > FRESH_MS && !revalidating.has(key)) {
      revalidating.add(key);
      fetchUpstream(url.pathname, url.search, hit.head.etag)
        .catch(() => null)
        .finally(() => revalidating.delete(key));
    }
    return;
  }

  try {
    const fresh = await fetchUpstream(url.pathname, url.search, "");
    if (fresh === "unchanged") {
      // Only reachable with an etag, which a miss never sends.
      res.writeHead(502, { "content-type": "text/plain" }).end("unexpected 304");
      return;
    }
    serveMirrored(res, fresh.head, fresh.body, isHead);
  } catch (err) {
    res.writeHead(502, { "Content-Type": "text/html; charset=utf-8" });
    res.end(
      `<!doctype html><meta charset="utf-8"><title>Promtly bridge</title>` +
        `<body style="background:#0B0F14;color:#F8FAFC;font:14px/1.6 system-ui;padding:48px;max-width:36rem">` +
        `<h1 style="font-weight:600">Cannot reach the board</h1>` +
        `<p style="color:#94A3B8">The bridge is running, but it could not fetch ` +
        `<code>${UPSTREAM}</code> and has nothing cached for this page yet: ` +
        `${String(err && err.message ? err.message : err)}</p>` +
        `<p style="color:#6F7E94">Open the launcher once with a connection and it will work ` +
        `offline after that. Pads still copy either way.</p></body>`,
    );
  }
}

const server = http.createServer(async (req, res) => {
  const origin = req.headers.origin;
  const allowed = typeof origin === "string" && ALLOWED_ORIGINS.has(origin);
  const url = new URL(req.url || "/", `http://127.0.0.1:${PORT}`);

  if (req.method === "OPTIONS") {
    if (!allowed) {
      res.writeHead(403).end();
      return;
    }
    res.writeHead(204, corsHeaders(origin)).end();
    return;
  }

  // Anything that is not this process's own API is the mirrored board.
  // Navigations carry no Origin header at all, so this has to come before
  // the origin check below or opening the local board 403s.
  if (!API_PATHS.has(url.pathname)) {
    await proxyUpstream(req, res, url);
    return;
  }

  // Endpoints that act on the machine require a browser that named itself.
  // A same-origin POST still sends Origin, so the mirrored board satisfies
  // this. Read-only endpoints also answer a same-origin GET (no Origin) and
  // plain curl.
  const readOnly =
    url.pathname === "/health" ||
    url.pathname === "/captures" ||
    // ⚠ GET only. /startup also WRITES on POST (it puts a script in the
    // Startup folder), and "read-only" here means "answers a request that
    // named no origin" - which a POST that changes the machine must not.
    (url.pathname === "/startup" && req.method === "GET") ||
    (url.pathname === "/update" && req.method === "GET") ||
    url.pathname === "/chairs" ||
    url.pathname.startsWith("/local/");
  if (!readOnly && !allowed) {
    send(res, 403, { ok: false, error: "origin not allowed" }, undefined);
    return;
  }
  if (readOnly && typeof origin === "string" && !allowed) {
    send(res, 403, { ok: false, error: "origin not allowed" }, undefined);
    return;
  }

  try {
    if (req.method === "GET" && url.pathname === "/health") {
      let target = "";
      let armed = false;
      if (driver) {
        try {
          const reply = await driver.target();
          target = reply.title;
          armed = reply.extra === "1";
        } catch {
          target = "";
        }
      }
      send(
        res,
        200,
        {
          ok: true,
          version: VERSION,
          platform: process.platform,
          supported,
          target,
          armed,
          captures: captures.length,
          hotkeys: hotkeys ? hotkeys.registered : null,
          latest: upstreamVersion,
          updateAvailable: updateAvailable(),
          // A checkout's bridge is updated with git; the UI hides the badge
          // rather than offering something that will refuse.
          updatable: !isDevelopmentCopy(),
        },
        origin,
      );
      return;
    }

    if (req.method === "GET" && url.pathname === "/local/version") {
      res.writeHead(200, { "Content-Type": "text/plain", "Cache-Control": "no-store" });
      res.end(localStamp());
      return;
    }

    if (
      req.method === "GET" &&
      (url.pathname === "/local/theme.css" || url.pathname === "/local/custom.js")
    ) {
      const isCss = url.pathname.endsWith(".css");
      res.writeHead(200, {
        "Content-Type": isCss ? "text/css; charset=utf-8" : "application/javascript; charset=utf-8",
        "Cache-Control": "no-store",
      });
      res.end(readLocal(isCss ? THEME_FILE : CUSTOM_JS));
      return;
    }

    if (req.method === "GET" && url.pathname === "/captures") {
      send(res, 200, { ok: true, captures }, origin);
      return;
    }

    if (req.method === "POST" && url.pathname === "/captures/clear") {
      const body = await readJson(req);
      const ids = Array.isArray(body.ids) ? new Set(body.ids) : null;
      const before = captures.length;
      for (let i = captures.length - 1; i >= 0; i -= 1) {
        if (!ids || ids.has(captures[i].id)) captures.splice(i, 1);
      }
      send(res, 200, { ok: true, cleared: before - captures.length }, origin);
      return;
    }

    // Wearing a pack's look. Writes exactly one file, always the same one.
    //
    // ⚠ There is deliberately NO write endpoint for custom.js. A stylesheet
    // cannot execute, so the worst a hostile theme can do is hide things;
    // script is a different category and stays something you place by hand.
    if (req.method === "POST" && url.pathname === "/local/theme") {
      const body = await readJson(req);
      const css = typeof body.css === "string" ? body.css : "";
      if (css.length > 400000) {
        send(res, 400, { ok: false, error: "theme too large" }, origin);
        return;
      }
      try {
        ensureLocalDir();
        writeFileSync(THEME_FILE, css, "utf8");
        log(`theme replaced (${css.length} chars) — the open window will follow`);
        send(res, 200, { ok: true, path: THEME_FILE }, origin);
      } catch (err) {
        send(res, 500, { ok: false, error: String(err && err.message ? err.message : err) }, origin);
      }
      return;
    }

    if (req.method === "GET" && url.pathname === "/chairs") {
      if (!driver) {
        send(res, 200, { ok: true, chairs: [] }, origin);
        return;
      }
      const reply = await driver.chairs();
      const chairs = reply.title
        .split("\n")
        .filter(Boolean)
        .map((line) => {
          const [name, title, alive] = line.split("\t");
          return { name, title: title || "", alive: alive === "1" };
        });
      send(res, 200, { ok: true, chairs }, origin);
      return;
    }

    if (req.method === "POST" && url.pathname === "/chairs/seat") {
      if (!driver) {
        send(res, 200, { ok: false, error: "unsupported platform" }, origin);
        return;
      }
      const body = await readJson(req);
      const name = typeof body.name === "string" ? body.name.trim().slice(0, 40) : "";
      if (!name) {
        send(res, 400, { ok: false, error: "name required" }, origin);
        return;
      }
      const reply = await driver.seat(name);
      log(`seated "${name}" = ${reply.title || "(untitled)"}`);
      send(res, 200, { ok: true, name, title: reply.title }, origin);
      return;
    }

    if (req.method === "POST" && url.pathname === "/chairs/unseat") {
      if (!driver) {
        send(res, 200, { ok: false, error: "unsupported platform" }, origin);
        return;
      }
      const body = await readJson(req);
      const name = typeof body.name === "string" ? body.name.trim() : "";
      await driver.unseat(name);
      send(res, 200, { ok: true }, origin);
      return;
    }

    /**
     * RELAY - one text, several chairs, in turn.
     *
     * This is the Promtly x Parley primitive. Seating two models at one table
     * means putting the same briefing in front of each of them, and doing it
     * by hand is the friction the whole idea dies on.
     *
     * Every chair is verified the way a single paste is: focus must actually
     * land, or that chair is reported refused and the loop moves on. A partial
     * relay is reported honestly rather than as success.
     */
    if (req.method === "POST" && url.pathname === "/relay") {
      if (!driver) {
        send(res, 200, { ok: false, error: "unsupported platform" }, origin);
        return;
      }
      const body = await readJson(req);
      const text = typeof body.text === "string" ? body.text : "";
      const wanted = Array.isArray(body.chairs)
        ? body.chairs.filter((c) => typeof c === "string")
        : [];
      const submit = body.submit === true;
      if (!text || wanted.length === 0) {
        send(res, 400, { ok: false, error: "text and chairs required" }, origin);
        return;
      }
      const results = [];
      for (const name of wanted) {
        const reply = await driver.paste(text, submit, name);
        results.push({ chair: name, status: reply.status, target: reply.title });
        log(`relay -> ${name}: ${reply.status}${reply.title ? ` (${reply.title})` : ""}`);
        // A breath between windows: a chat box just typed into is often still
        // settling, and the next focus change can be refused if it lands on
        // top of the last one.
        await new Promise((r) => setTimeout(r, 260));
      }
      send(res, 200, { ok: results.every((r) => r.status === "ok"), results }, origin);
      return;
    }

    // Get out of the way: put the window you summoned from back in front.
    if (req.method === "POST" && url.pathname === "/dismiss") {
      if (!driver) {
        send(res, 200, { ok: false, error: "unsupported platform" }, origin);
        return;
      }
      const reply = await driver.dismiss();
      send(res, 200, { ok: reply.status === "ok", target: reply.title }, origin);
      return;
    }

    if (req.method === "POST" && url.pathname === "/window") {
      if (!driver) {
        send(res, 200, { ok: false, error: "unsupported platform" }, origin);
        return;
      }
      const body = await readJson(req);
      const mode = body.mode === "peek" || body.mode === "hide" ? body.mode : "full";
      const reply = await driver.place(mode);
      send(res, 200, { ok: reply.status === "ok", status: reply.status, mode }, origin);
      return;
    }

    // Start-with-Windows as a TOGGLE rather than a flag you have to know.
    //
    // It was already there as --install-startup, which meant the one thing
    // that decides whether this is a tool or a demo - is it running when you
    // reach for it - needed a terminal and a remembered argument. On a second
    // machine that is the step you skip.
    if (url.pathname === "/startup") {
      if (process.platform !== "win32") {
        send(res, 200, { ok: false, installed: false, error: "windows only" }, origin);
        return;
      }
      if (req.method === "GET") {
        send(res, 200, { ok: true, installed: startupInstalled() }, origin);
        return;
      }
      if (req.method === "POST") {
        const body = await readJson(req);
        const code = manageStartup(body.install === false ? "uninstall" : "install");
        send(res, 200, { ok: code === 0, installed: startupInstalled() }, origin);
        return;
      }
    }

    if (url.pathname === "/update") {
      if (req.method === "GET") {
        await checkForUpdate(true);
        send(
          res,
          200,
          { ok: true, version: VERSION, latest: upstreamVersion, updateAvailable: updateAvailable() },
          origin,
        );
        return;
      }
      if (req.method === "POST") {
        const result = await installUpdate();
        send(res, 200, { ...result, from: VERSION }, origin);
        return;
      }
    }

    if (req.method === "POST" && (url.pathname === "/paste" || url.pathname === "/copy")) {
      if (!driver) {
        send(res, 200, { ok: false, error: `unsupported platform: ${process.platform}` }, origin);
        return;
      }
      const body = await readJson(req);
      const text = typeof body.text === "string" ? body.text : "";
      if (!text) {
        send(res, 400, { ok: false, error: "text required" }, origin);
        return;
      }
      const reply =
        url.pathname === "/paste"
          ? await driver.paste(
              text,
              body.submit === true,
              typeof body.chair === "string" ? body.chair : "",
            )
          : await driver.copy(text);
      // A status code is not an explanation. Every refusal here has a
      // different thing the person has to DO about it, so each one says what.
      const REASONS = {
        notarget: "No window to paste into — every candidate was minimised or ineligible.",
        nofocus:
          "Windows refused the switch, so the keystroke was not sent. Nothing was pasted anywhere.",
        clipfail: "Could not write to the clipboard; another app is holding it.",
      };
      send(
        res,
        200,
        {
          ok: reply.status === "ok",
          status: reply.status,
          target: reply.title,
          ...(reply.status !== "ok" && REASONS[reply.status] ? { error: REASONS[reply.status] } : {}),
        },
        origin,
      );
      log(
        reply.status === "ok"
          ? `pasted ${text.length} chars into "${reply.title}"${body.submit === true ? " and submitted" : ""}`
          : `paste ${reply.status}${reply.title ? ` (target "${reply.title}")` : ""}`,
      );
      return;
    }

    send(res, 404, { ok: false, error: "not found" }, origin);
  } catch (err) {
    send(res, 500, { ok: false, error: String(err && err.message ? err.message : err) }, origin);
  }
});

server.on("error", (err) => {
  if (err && err.code === "EADDRINUSE") {
    log(`port ${PORT} is already in use — a bridge is probably already running.`);
    process.exit(1);
  }
  throw err;
});

server.listen(PORT, "127.0.0.1", () => {
  pruneCache();
  // Behind the response, never blocking start: a bridge that will not come up
  // because promtly.dev is slow is worse than one that does not know it is old.
  setTimeout(() => void checkForUpdate(true), 2_000).unref?.();
  log(`Promtly bridge ${VERSION} listening on http://127.0.0.1:${PORT}`);
  if (!supported) {
    log(`platform ${process.platform} is not supported yet — clipboard, paste and`);
    log("hotkeys are Windows-only. The board is mirrored here but pads only copy.");
  } else {
    log("");
    log(`  the full board:  http://127.0.0.1:${PORT}/board`);
    log("");
    log("     Served from here on purpose: same-origin with this process, so");
    log("     there is no browser permission to negotiate. promtly.dev works");
    log("     too, but Chrome may gate its request and then pads only copy.");
  }
  if (ensureLocalDir()) {
    log("");
    log("  make it yours — these are on your machine and an assistant can edit them:");
    log(`     ${THEME_FILE}`);
    log(`     ${GUIDE_FILE}  (hand this to Claude or ChatGPT)`);
    log("     saved changes appear in the open window in about a second.");
  }

  log("");
  log("leave this window open. Ctrl+C to stop.");

  // Show, do not instruct. "Run it, then go and open a URL" is a step people
  // do not complete; opening the launcher once on start means the first thing
  // you see after double-clicking is the thing working. --no-open opts out.
  const suppressOpen = process.env.PROMTLY_NO_OPEN === "1" || argv.includes("--no-open");
  if (supported && !suppressOpen) {
    setTimeout(async () => {
      // !! Only if one is not already open.
      //
      // This opened unconditionally, so every restart of the bridge left
      // another launcher window behind - and they are Chrome --app windows,
      // which do not show up under Get-Process MainWindowTitle, so they pile
      // up invisibly. Restarting the bridge during a day's work is normal;
      // collecting a window each time is not.
      try {
        const state = await driver.launcherState();
        if (state.exists) {
          log("launcher already open — raising it instead of opening another");
          await driver.place("full");
          return;
        }
      } catch {
        // If the helper cannot answer, opening one is the better failure.
      }
      log("opening the launcher so you can see it working (--no-open to skip)");
      openLauncherWindow();
    }, 700);
  }
});

for (const signal of ["SIGINT", "SIGTERM"]) {
  process.on(signal, () => {
    if (driver && driver.proc) driver.proc.kill();
    if (hotkeys && hotkeys.proc) hotkeys.proc.kill();
    server.close(() => process.exit(0));
    setTimeout(() => process.exit(0), 500);
  });
}
